### ISSUE TITLE
Issue with configs and kera

### ISSUE THREAD

**Issue by Seneca-Sys** [ariaaan/traffic-signs-detector#22]
Hi all,

I have installed everything as per the readme. However, i get the following error when running the example script 

````
Traceback (most recent call last):
  File "/home/box/Desktop/traffic-signs-detector/detector/detector.py", line 268, in create_detector_from_file
    classifier_cfg['skip_classes'])
  File "/home/box/Desktop/traffic-signs-detector/detector/classifier.py", line 13, in __init__
    self.__classifier_model = keras.models.model_from_json(model_json)
  File "/home/box/miniconda3/envs/myenv/lib/python3.5/site-packages/keras/models.py", line 346, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/box/miniconda3/envs/myenv/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/box/miniconda3/envs/myenv/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/box/miniconda3/envs/myenv/lib/python3.5/site-packages/keras/models.py", line 1318, in from_config
    if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge':
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_image.py", line 4, in <module>
    detector = create_detector_from_file('./cfg/example.config.json')
  File "/home/box/Desktop/traffic-signs-detector/detector/detector.py", line 281, in create_detector_from_file
    raise FormatNotSupportedException('The configuration file does not seems to be valid')
detector.exceptions.FormatNotSupportedException: The configuration file does not seems to be valid
````

yes i have downloaded the weight file from the link i found in the previous issues, and yes i am familiar that someone else had the same issue before... however how they managed to solve it was not clear to me. Therefore, i humbly ask for some help solving this issue.

thank you!

**Comment by alevikpes** [comment]
I guess, you are using the default `./cfg/example.config.json`, but you need to specify in that config correct files in your file structure. In my case I have a separate `config.json`, which looks like this:
```json
{
    "localizer": {
        "model": "/path/to/your/project/data/yolo/full/trafficsigns.cfg",
        "weights": "/path/to/your/project/data/yolo/full/trafficsigns.weights",
        "threshold": 0.24
    },
    "cropper": {
        "crop_percent": 0.25,
        "force_square": true
    },
    "classifier": {
        "model": "/path/to/your/project/data/classifier/trafficsigns.json",
        "weights": "/path/to/your/project/data/classifier/weights.hdf5",
        "labels": "/path/to/your/project/data/classifier/classes.txt",
        "threshold": 0.9,
        "skip_classes": [11, 14, 17, 18, 19]
    },
    "detector": {
        "images_path": "/path/to/your/project/data/classifier/classes/",
        "sounds_path": "/path/to/your/project/data/sounds/"
    }
}
```
And you need to have all those files available, of course.

Note, that you need to specify this `config.json` or whichever you are using, in the `example_video.py` and `example_image.py` before running them.

PS: I think, this file is generated by the `init_config.py`, so you need to specify the correct file paths in it, if you are using this init file. Generally, you do not need to use the init file but specify the correct paths in the config.json.

**Comment by alevikpes** [comment]
I guess, you may have been using the wrong file on [this line](https://github.com/ariaaan/traffic-signs-detector/blob/master/cfg/example.config.json#L13). The file in the repo is an empty file, but it should be some weights file. In my case I use `weights.hdf5`, but I do not remember, where I got it.

**Comment by nick0clayne** [comment]
> I guess, you may have been using the wrong file on [this line](https://github.com/ariaaan/traffic-signs-detector/blob/master/cfg/example.config.json#L13). The file in the repo is an empty file, but it should be some weights file. In my case I use `weights.hdf5`, but I do not remember, where I got it.

Can you share the weights.hdf5 file, please

**Comment by alevikpes** [comment]
> > I guess, you may have been using the wrong file on [this line](https://github.com/ariaaan/traffic-signs-detector/blob/master/cfg/example.config.json#L13). The file in the repo is an empty file, but it should be some weights file. In my case I use `weights.hdf5`, but I do not remember, where I got it.
> 
> Can you share the weights.hdf5 file, please

I cannot share - it is around 11 GB file. I downloaded it from somewhere, can't remember where

**Comment by prajwalan364** [comment]
Any one have weights.h5 file

**Comment by webbrain-one** [comment]
Hi there! Thanks for the detailed report. I’ve opened a pull request to address this: https://github.com/ariangilesgarcia/traffic-signs-detector/pull/32

The error you're seeing is caused by a compatibility mismatch between your Keras version and how the model JSON is being deserialized. The PR updates the configuration parsing logic to correctly handle the model structure, which resolves the `KeyError` and prevents the `FormatNotSupportedException` from triggering.

Feel free to test out the PR branch and let me know if it resolves the issue on your setup! Thanks again for bringing this to attention. 🚗✨
